# @package eval.forget
# Evaluator for forget dataset from training

defaults:
  - forget_metrics:
    - forget_Q_A_Prob

handler: TrainDatasetEvaluator
output_dir: ${paths.output_dir}
metrics: {}
overwrite: false
batch_size: 32
question_key: "question"
