defaults:
  - _self_
  - model: Llama-3.1-8B-Instruct
  - trainer: finetune
  - data: finetune
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null

mode: train
task_name: judy-test-benchmark